import type { Resource } from "@/routes/crm/constants.js";

const WRITE_ALLOWLISTS: Record<Resource, readonly string[]> = {
  contacts: [
    "firstName",
    "lastName",
    "gender",
    "title",
    "email",
    "emailJsonb",
    "phoneJsonb",
    "background",
    "avatar",
    "firstSeen",
    "lastSeen",
    "hasNewsletter",
    "status",
    "tags",
    "companyId",
    "linkedinUrl",
    "customFields",
  ],
  companies: [
    "name",
    "sector",
    "size",
    "linkedinUrl",
    "website",
    "phoneNumber",
    "address",
    "zipcode",
    "city",
    "stateAbbr",
    "country",
    "description",
    "revenue",
    "taxIdentifier",
    "logo",
    "contextLinks",
    "customFields",
  ],
  deals: [
    "name",
    "companyId",
    "contactIds",
    "category",
    "stage",
    "description",
    "amount",
    "expectedClosingDate",
    "index",
    "customFields",
  ],
  contact_notes: ["contactId", "text", "date", "status", "attachments"],
  deal_notes: ["dealId", "type", "text", "date", "attachments"],
  tasks: ["contactId", "type", "text", "dueDate", "doneDate"],
  crm_users: [],
  tags: ["name", "color"],
  configuration: ["config"],
  automation_rules: ["name", "enabled", "workflowDefinition", "lastRunAt"],
  companies_summary: [],
  contacts_summary: [],
};

export function getWriteAllowlist(resource: Resource): Set<string> {
  return new Set(WRITE_ALLOWLISTS[resource] ?? []);
}
