/**
 * Maps CRM resource names to NocoDB table IDs.
 *
 * Table IDs are generated by NocoDB during introspection and look like "tbl_xxx".
 * This map is populated at runtime from the /api/nocodb-config endpoint.
 */

let _tableMap: Record<string, string> = {};

export function configureTableMap(map: Record<string, string>) {
  _tableMap = { ...map };
}

export function getTableId(resource: string): string {
  const tableId = _tableMap[resource];
  if (!tableId) {
    throw new Error(
      `No NocoDB table ID for resource "${resource}". Available: ${Object.keys(_tableMap).join(", ")}`,
    );
  }
  return tableId;
}

export function getTableMap(): Record<string, string> {
  return { ..._tableMap };
}
